### PR TITLE
Update recovery.fstab

### PR DESCRIPTION
**Pull request by Flyhalf205**
To let USB Storage mount the external sdcard instead of mounting internal

### CODE REVIEW

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.org/wiki/Howto:_Gerrit

Thanks!

**Comment by koush** [comment]
You can set the lun files in recovery.fstab to allow mounting both.

**Comment by Flyhalf205** [comment]
Can we still get this changed please? All of our s-on installers copy over a PH98IMG.zip to the sdcard which must be on the external sdcard but in this situation it will copy over to the internal sdcard. Thank you.

**Comment by koush** [comment]
Hi, I mentioned the fix in my previous comment. CWM supports mounting both sdcards.

**Comment by Snuzzo** [comment]
There is some confusion as to what FlyHalf is explaining. For proper use of the "Any Kernel installer" with S-On capabilties the installer must place the ph98img.zip on the external sd to function properly.

In this case it is attempting to create the PH98IMG on the internal sd card, which when rebooted to bootloader to flash said boot.img from the PH98IMG the bootloader cannot load it.

The proper wording of the commit should have been as such:
"To let USB Storage mount the external sdcard as sdcard instead of mounting internal as sdcard"

**Pull request closed without merging**
